### ISSUE TITLE
사용자는 스타일이 적용된 게시글 페이지를 확인할 수 있다.

### ISSUE THREAD

**Issue by secret-papa** [secret-papa/blog#34]
**Is your feature request related to a problem? Please describe.**
게시글 페이지 스타일 적용이 되지 않아서, 게시글의 가독성이 떨어지는 문제

**Describe the solution you'd like**
mdx styling과 mdx가 아닌 요소에 대한 스타일링으로 게시글 페이지의 가독성을 올림

**Additional context**
[MDX 스타일링](https://github.com/sindresorhus/github-markdown-css)
[Code Block 스타일링](https://github.com/FormidableLabs/prism-react-renderer)
[블로그 참고](https://velog.io/@gomiseki/Next.js%EC%97%90%EC%84%9C-MDX-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A5%BC-%EC%8A%A4%ED%83%80%EC%9D%BC%EB%A7%81%ED%95%98%EA%B8%B0-%ED%8E%B8%ED%95%98%EA%B2%8C)

**Subtask**
- [x] github markdown css 적용
  - [x] code block 스타일링
- [x] 이전, 다음 글 버튼 영역 스타일링
- [x] 게시글 목록으로 이동
